version: "3.8"
services:
  # Main backend container
  express-backend:
    build:
      context: ./backend
      dockerfile: server.Dockerfile
    container_name: express-backend
    environment:
      - HOST=${EXPRESS_BACKEND_HOST}
      - PORT=${EXPRESS_BACKEND_PORT}
      - MONGODB_URL=${MONGODB_URL}
    ports:
      - "${EXPRESS_BACKEND_PORT}:${EXPRESS_BACKEND_PORT}"
    depends_on:
      - mongodb
  # Database container
  mongodb:
    image: mongo:latest
    container_name: mongodb
    expose:
      - ${MONGODB_PORT}
    ports:
      - "${MONGODB_PORT}:${MONGODB_PORT}"
    volumes:
      - mongodb_data_container:/data/db

# Keeps the MongoDB data consistent between shutdowns
volumes:
  mongodb_data_container:

