version: "3.8"
services:
  # Frontend container
  angular-frontend:
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
    container_name: angular-frontend
    environment:
      - PORT=${ANGULAR_FRONTEND_PORT}
      - NG_APP_BE_HOST=${EXPRESS_BACKEND_HOST}
      - NG_APP_BE_PORT=${EXPRESS_BACKEND_PORT}
    ports:
      - "${ANGULAR_FRONTEND_PORT}:${ANGULAR_FRONTEND_PORT}"
    depends_on:
      - express-backend
  # Main backend container
  express-backend:
    build:
      context: ./
      dockerfile: ./backend/public-api/server.Dockerfile
    container_name: express-backend
    environment:
      - HOST=${EXPRESS_BACKEND_HOST}
      - PORT=${EXPRESS_BACKEND_PORT}
      - MONGODB_URL=${MONGODB_URL}
    ports:
      - "${EXPRESS_BACKEND_PORT}:${EXPRESS_BACKEND_PORT}"
    depends_on:
      - mongodb
      - python-backend
    # Data-science backend container
  python-backend:
    build:
      context: ./
      dockerfile: ./backend/data-science/Dockerfile
    container_name: python-backend
    environment:
      - HOST=${PYTHON_BACKEND_HOST}
      - PORT=${PYTHON_BACKEND_PORT}
    ports:
      - "${PYTHON_BACKEND_PORT}:${PYTHON_BACKEND_PORT}"
  # Database container
  mongodb:
    image: mongo:latest
    container_name: mongodb
    expose:
      - ${MONGODB_PORT}
    ports:
      - "${MONGODB_PORT}:${MONGODB_PORT}"
    volumes:
      - mongodb_data_container:/data/db

# Keeps the MongoDB data consistent between shutdowns
volumes:
  mongodb_data_container:
