name: Backend-CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - "backend/public-api/**"

jobs:
  ProjectErrorsTest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: Setup backend
        run: npm run setup:backend

      - name: Run formatting checks
        run: npm run format
        working-directory: backend/public-api

      - name: Run linting checks
        run: npm run lint
        working-directory: backend/public-api

      - name: Run tests
        run: npm test
        working-directory: backend/public-api
