name: Docker-Compose

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - "backend/**"
      - "frontend/**"

jobs:
  DockerComposeTest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Execute Docker Compose
        run: docker-compose up -d

      - name: Run Health Check
        run: ./.github/scripts/health_check.sh

      - name: Stop and clean up services
        run: docker-compose down
