name: Backend CI

on:
  pull_request:
    branches:
      - main
    paths:
      - "backend/**"

jobs:
  ProjectErrorsTest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: Setup project
        run: npm run setup

      - name: Run static checks
        run: cd backend/ && npm run lint

      - name: Run unit tests
        run: cd backend/ && npm test
